name: Build and test

on: [ pull_request ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21

      - name: Build with Gradle
        run: ./gradlew clean build --stacktrace --info --no-daemon
